name: Build and Deploy
on:
  push:
    branches:
      - api

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Deploy to Server
        uses: ngocquyhoang/deploy@laravel
        with:
          user: dhaker
          host: 51.91.255.126
          path: /var/www/vhosts/vpsdev.wi-mobi.com/httpdocs
          owner: dhaker
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: dhaker
          host: 51.91.255.126
          password: 01131994
          script: 'cd /var/www/vhosts/vpsdev.wi-mobi.com/httpdocs && ./server_deploy.sh'
